// <auto-generated />
using HeroAPI.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HeroAPI.Data.Migrations
{
    [DbContext(typeof(HeroDbContext))]
    partial class HeroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HeroAPI.Data.Entities.Hero", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Classification")
                        .HasColumnType("int(11)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("enum('Male', 'Female')");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OwnName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Powers")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Universe")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("id");

                    b.ToTable("Heroes","HeroAPI");
                });
#pragma warning restore 612, 618
        }
    }
}
